apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 15
  selector:
    matchLabels:
      project: a3-updated
  template:
    metadata:
      labels:
        project: a3-updated
    spec:
      containers:
      - name: container-updated
        image: httpd:latest
        ports:
        - containerPort: 8080

